name: poliedro_server
description: Backend server para autenticação MongoDB
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mongo_dart: ^0.10.3
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.0
  dotenv: ^4.2.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^5.0.0
